# Generated by Django 2.2 on 2020-08-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='foobarbaz', max_length=255),
            preserve_default=False,
        ),
    ]
