# Generated by Django 2.2 on 2020-08-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users_who_like',
            field=models.ManyToManyField(null=True, related_name='liked_books', to='login_app.User'),
        ),
    ]
