# Generated by Django 2.2 on 2020-08-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_auto_20200815_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='quotes_app.User'),
        ),
    ]
